### PR TITLE
rough idea how to make it less verbose

### PR DESCRIPTION
**Pull request by calvinmetcalf**
haven't checked perf

### CODE REVIEW

**Comment by indutny** [comment]
This is not going to work. Here are results with your patch and with master (from elliptic):

```
# with patch
verify: 10545.672ms
sign: 3968.732ms

# without
true
verify: 6560.543ms
sign: 2792.045ms
```

**Comment by indutny** [comment]
The reasons are, accessing context variable `c`. Placing function inside of that function, so it can't be inlined efficiently.

**Comment by calvinmetcalf** [comment]
ok rejiggered it so it was inlineable but it hits the 'cumulative AST node limit'

**Comment by dcousens** [comment]
> 'cumulative AST node limit'

How are you measuring this OOI?

**Comment by calvinmetcalf** [comment]
was running it in node with the --trace-inline flag

**Comment by dcousens** [comment]
Closing unless someone else wants to take up the reigns

**Pull request closed without merging**
