### PR TITLE
Add `padTo` option to toArray

### PR DESCRIPTION
**Pull request by sublimator**

### CODE REVIEW

**Comment by indutny** [comment]
Landed and released, thanks!

**Comment by indutny** [comment]
@sublimator may I ask you to create a PR for readme as well? Sorry forgot to say this before landing :(

**Comment by sublimator** [comment]
How do you feel about allowing the padTo to work as the first arg, while I'm at it?

**Comment by indutny** [comment]
@sublimator this will break stuff :( Let's keep it as it is

**Pull request closed without merging**
