### PR TITLE
lib: fix for negative numbers: imuln, modrn, idivn

### PR DESCRIPTION
**Pull request by fanatid**

### CODE REVIEW

**Comment by fanatid** [comment]
@indutny can you review, merge and release? :)

**Comment by fanatid** [comment]
@dcousens are we waiting more tests from me? :)

**Comment by dcousens** [comment]
@fanatid aye,  I was asking,  it seems important to only cover with 1 test...

**Comment by fanatid** [comment]
@dcousens additionally fixed modrn, idivn

**Comment by dcousens** [comment]
@indutny LGTM, can you ACK?

**Comment by fanatid** [comment]
Thanks. Can you publish new version? (This is not only one change what was introduced from last version)

**Pull request merged**
