### PR TITLE
failing test for the 4.1.0 reversion

### PR DESCRIPTION
**Pull request by calvinmetcalf**
basically mont and red are not getting the same results

### CODE REVIEW

**Comment by calvinmetcalf** [comment]
re  #63

**Comment by indutny** [comment]
argh... thanks for finding this out

**Comment by indutny** [comment]
It doesn't look like it was working before, either... can you confirm?

**Comment by indutny** [comment]
Wait, of course they are different. You are comparing representations in reduction context. Try calling `fromRed()` on them ;)

**Comment by calvinmetcalf** [comment]
damn you are right back to square one

**Pull request closed without merging**
