### PR TITLE
Semver-major release: 5.0.0

### PR DESCRIPTION
**Pull request by fanatid**
First, @indutny @calvinmetcalf thanks for trust and allowance to maintain this project. And sorry for delay.

Initially, I planned fill CHANGELOG.md and submit PR with minor version, but almost immediately I remembered that `master` branch already have semver-major changes which was never published. So I decide:

1) Summarize all current changes, submit PR with CHANGELOG for semver-major version: `5.0.0`
2) Merge/update/close current not semver-major PR's and release semver-minor version: `5.1.0` and so on..
3) Start work on unfinished semver-major changes from #129 for version: `6.0.0`

I'm not sure that I'll able finish `6.0.0`, but I'll try do this.

`5.0.0` can be considered as intermediate version. It's fastest way receive bn.js with patches from ~2 last years.

--

@indutny @calvinmetcalf I'd prefer not release version `5.0.0` without ACK. Are you ok with this plan?
No need merge this PR, this mostly preview. If you agree with proposed process, I'll commit changes directly to master.

### CODE REVIEW

**Comment by axic** [comment]
Can some other renames make it into the release to make the API more consistent?

**Comment by fanatid** [comment]
Do you mean `andln` => `andrn`? I think yes, this should be simple change.

**Comment by indutny** [comment]
:+1:

**Comment by fanatid** [comment]
Published `v5.0.0` (https://github.com/indutny/bn.js/commit/8a8d9bad8f7170b1f2bd48ebb2bc97f1e39beb74)

**Pull request closed without merging**
