### PR TITLE
Reject decimal input

### PR DESCRIPTION
**Pull request by axic**
As discussed in https://github.com/indutny/bn.js/issues/90

### CODE REVIEW

**Comment by indutny** [comment]
Does it affect benchmarks?

**Comment by axic** [comment]
Seems like my comments didn't get posted here back in December. Unfortunately it does affect benchmarks so I was thinking about others ways to do it. Perhaps the best would be having two input functions: a *safe* (for "user input") and an *unsafe* one (for speed, e.g. the current implementation).

Any ideas about an API for the above?

**Comment by indutny** [comment]
I'm not sure about it myself. Perhaps, `BN.checkedFrom(string, 'hex')`?

**Comment by indutny** [comment]
Preemptively added `semver-major` tag per your request.

**Comment by fanatid** [comment]
Why not land this PR in `4.x`?
@axic I think only *safe* should be here

**Comment by indutny** [comment]
Landed test in 9173bc2, the issue was fixed in different commit. Thank you!

**Pull request closed without merging**
