### PR TITLE
Streamlined GCD procedure to be strictly O(N^2) instead of O(N^3)

### PR DESCRIPTION
**Pull request by alexeykudinkin**
2.5x speedup upon 3072b BNs.

### CODE REVIEW

**Comment by indutny** [comment]
@alexeykudinkin may I ask you to run `npm test` and fix jshint failures?

**Comment by indutny** [comment]
I'm afraid this PR makes `gcd` 10x times slower than it is right now.

**Comment by indutny** [comment]
Mind fixing lint issues, please?

**Comment by alexeykudinkin** [comment]
No doubt. Will fix them today.

**Comment by alexeykudinkin** [comment]
Done.

**Comment by indutny** [comment]
Landed in 294d637, thank you!

**Pull request closed without merging**
