### PR TITLE
bn: introduce .isNeg()

### PR DESCRIPTION
**Pull request by axic**

### CODE REVIEW

**Comment by indutny** [comment]
Looks like the lint is no longer passing after your latest commit.

**Comment by indutny** [comment]
Otherwise, LGTM. Please let me know once it will pass again, and I will take another look. Thanks!

**Comment by axic** [comment]
Honestly I don't think that is caused by my change. ```npm test``` runs without failures on my setup (which uses node v0.12.7). For the sake of testing I've also installed v0.10.40 and that works too.

**Comment by indutny** [comment]
Landed and released, thank you!

**Comment by axic** [comment]
Thank you!

**Pull request closed without merging**
