### PR TITLE
readme: update .toArray

### PR DESCRIPTION
**Pull request by sublimator**

### CODE REVIEW

**Comment by sublimator** [comment]
Something to consider: currently this does nothing about when the array is already larger than padTo.

**Comment by indutny** [comment]
Hell yes, thanks!

Interesting, maybe we should make it throw? I doubt that the code that works with this will ever handle such results properly.

**Comment by indutny** [comment]
Landed in 495165a

**Comment by sublimator** [comment]
Throwing sounds good to me

**Comment by sublimator** [comment]
Opened a pull request with strict length semantics (renamed padTo to length in the process)

**Pull request closed without merging**
