### PR TITLE
Fix BN v5/v4 interoperability issue for v5.x

### LINKED ISSUE #239: k256 MPrime missing strip()
Related to issue: https://github.com/indutny/elliptic/issues/191#issuecomment-569888758

@fanatid said he saw the same issue as the one below where strip() is missing. I'm posting it here in hopes for a minor patch with a workaround.

```sh
 FAIL  tests/apis/ava/keychain.test.ts (5.154s)
  AssetsKeyPair
    ✕ Creation Empty (403ms)

  ● AssetsKeyPair › Creation Empty

    TypeError: r.strip is not a function



      at K256.ireduce (node_modules/elliptic/node_modules/bn.js/lib/bn.js:2975:9)
      at Red.imod (node_modules/elliptic/node_modules/bn.js/lib/bn.js:3147:39)
      at Red.mul (node_modules/elliptic/node_modules/bn.js/lib/bn.js:3211:17)
      at BN.redMul (node_modules/bn.js/lib/bn.js:2984:21)
      at JPoint.eqXToP (node_modules/elliptic/lib/elliptic/curve/short.js:909:36)
      at EC.verify (node_modules/elliptic/lib/elliptic/ec/index.js:191:12)
      at AssetsKeyPair.verify (src/apis/ava/keychain.ts:2440:17)
      at Object.<anonymous> (tests/apis/ava/keychain.test.ts:15:19)
```

from code:

```ts    
/**
     * Verifies that the private key associated with the provided public key produces the signature associated with the given message.
     * 
     * @param msg The message associated with the signature
     * @param sig The signature of the signed message
     * 
     * @returns True on success, false on failure
     */
    verify = (msg:Buffer, sig:Buffer):boolean => { 
        let sigObj:elliptic.ec.SignatureOptions = this._sigFromSigBuffer(sig);
        return ec.verify(msg, sigObj, this.keypair);
    }

    /**
     * @ignore
     */
    protected _sigFromSigBuffer = (sig:Buffer):elliptic.ec.SignatureOptions => {
        let r:BN = new BN(bintools.copyFrom(sig, 0, 32));
        let s:BN = new BN(bintools.copyFrom(sig, 32, 64));
        let recoveryParam:number = bintools.copyFrom(sig, 64, 65).readUIntBE(0, 1);
        let sigOpt = {
            r:r,
            s:s,
            recoveryParam:recoveryParam
        };
        return sigOpt;
    }
```

### PR DESCRIPTION
**Pull request by holgerd77**
Fixes #239 on the 5.x branch

Made sure that the respective code part is actually touched by the unit tests.

(second try following #247 after CI problems)

### CODE REVIEW

**Comment by holgerd77** [comment]
That's indeed strange. 😕

Maybe just do the fix yourself directly on the main repo, don't have to retain me as the author or something.

**Comment by holgerd77** [comment]
Ah no, did another short test (changing the code comments a little), didn't work.

Anyhow.

**Comment by fanatid** [comment]
CI: Looks like not only we have problem with it: https://github.community/t5/GitHub-Actions/Github-action-stuck-at-queue/td-p/38003/page/6

**Comment by holgerd77** [comment]
👍

**Comment by fanatid** [comment]
Published as `v5.1.2`.

**Comment by holgerd77** [comment]
Ok, I re-added the browser tests I commented out before on the wallet library PR https://github.com/ethereumjs/ethereumjs-wallet/pull/121, if `test-browser` check is running through we also have a "real-life" confirmation that this is working. 😄

**Comment by holgerd77** [comment]
Ok, can confirm, browser tests ran through.

**Pull request merged**
