### PR TITLE
Use semistandard

### LINKED ISSUE #58: Use semistandard for enforcing style
https://github.com/Flet/semistandard/

### PR DESCRIPTION
**Pull request by dcousens**
Resolves #58 

---

Currently this PR only does `test/` and `benchmarks/`.
@indutny can you ACK the style and changes before I spend the time to do `lib/`?

### CODE REVIEW

**Comment by indutny** [comment]
Sorry for delay. Whoa, this is very different from my code style :) Looks like I'm not even using a "half-standard" style.

I fully trust you on this, please go ahead and let's land it!

**Comment by fanatid** [comment]
What about [standard](https://github.com/feross/standard/)?
@dcousens probably https://www.npmjs.com/package/semistandard-format will speed up work on this PR

**Comment by indutny** [comment]
@fanatid there are several rules in "standard" that does not looks good to me. Especially the semicolons rule. I know that it is quite controversial topic. My position is different from "standard" on this.

**Comment by dcousens** [comment]
@indutny see the rebase.
Should be good to go, all tests pass.

**Comment by dcousens** [comment]
@indutny https://github.com/indutny/bn.js/pull/60?w=0 is definitely your friend for review.

**Comment by dcousens** [comment]
Though, due to `bn.js` being so large, GitHub isn't showing the diff, so you'll have to check it out locally.
At least you'll be able to check the other files though.

**Comment by indutny** [comment]
All landed, thank you!

**Comment by dcousens** [comment]
ping @flet

**Pull request closed without merging**
