### PR TITLE
lib: better and faster `isBN` check

### PR DESCRIPTION
**Pull request by indutny**
Fix: #133 

cc @dcousens @axic @calvinmetcalf @fanatid

### CODE REVIEW

**Comment by jprichardson** [comment]
LGTM.

**Comment by indutny** [comment]
Thank you @jprichardson !

If anyone else wants to leave a feedback, please do it in next 16 hours. I'll land it if no objections will be raised.

Thanks!

**Comment by dcousens** [comment]
LGTM

**Comment by indutny** [comment]
Alright, thanks everyone! Landing.

**Comment by indutny** [comment]
Landed in 1b5002e.

**Pull request closed without merging**
