### PR TITLE
Don't accept invalid characters

### PR DESCRIPTION
**Pull request by dchest**
Contructor from string accepted characters out of base range.
Fix by throwing exception when such character appears in the string.

_PS Spent the whole day trying to figure out why my code didn't work only to discover that I forgot to add 16 as base for constructor (similar to the test in this commit) :sweat_smile:_

### CODE REVIEW

**Comment by fanatid** [comment]
Related: https://github.com/indutny/bn.js/issues/90 https://github.com/indutny/bn.js/pull/91

**Comment by dchest** [comment]
@fanatid this one will just make sure that decoded number is less than base, but won't reject other characters, e.g. I think `:` and `;`, etc. (they are between numbers and letters in ASCII) will be accepted for base 16.

**Comment by fanatid** [comment]
semver-major btw

**Comment by indutny** [comment]
Landed in 9827640, thank you!

**Pull request closed without merging**
