### PR TITLE
tests: redSqrt with quadratic nonresidue

### PR DESCRIPTION
**Pull request by fanatid**
Details: #101

### CODE REVIEW

**Comment by indutny** [comment]
Heh... Looks like we did not understand each other after all. Sorry for this!

I will try to figure out test case that uses `elliptic` instead of raw-`bn.js` myself.

**Comment by fanatid** [comment]
Oh, just now recognize that you write elliptic in 101 :smile:

**Comment by axic** [comment]
@fanatid I think it probably makes sense having that test here too? After all it's `bn.js` methods :)

**Comment by fanatid** [comment]
ok, branch is restored now, Fedor can fetch and make cherry-pick as usual :)

**Comment by indutny** [comment]
@axic idk, I don't really want this method to throw, at least not right now. Maybe in next version?

**Pull request closed without merging**
